steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/octo-news/cra-cloud-run:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/octo-news/cra-cloud-run:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
   - 'run'
   - 'deploy'
   - 'cra-cloud-run'
   - '--image'
   - 'gcr.io/octo-news/cra-cloud-run:$COMMIT_SHA'
   - '--region'
   - 'us-west1'
   - '--platform'
   - 'managed'
images:
- 'gcr.io/octo-news/cra-cloud-run:$COMMIT_SHA'

